apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- cmap_service.ingress.yaml

namespace: abuse-api-dev

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/1"
      value:
        name: wiremock
        image: gdartifactory1.jfrog.io/docker-dcu-local/cmap_service/wiremock:dev
  target:
    kind: Deployment
    name: cmap-service
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/livenessProbe"
      value:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
  target:
    kind: Deployment
    name: cmap-service


images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/cmap_service
  newTag: dev

configMapGenerator:
- literals:
  - METRICS_PORT='9200'
  - LOGLEVEL=INFO
  - sysenv=dev
  - HTTP_ONLY='true'
  - REDIS='cmap-service-redis.abuse-api-dev.svc.cluster.local'
  name: env-specific-values
