import suds
from suds.client import Client
import xml.etree.ElementTree as ET

fkUrl = 'http://shopper.prod.phx3.gdg/WSCgdShopper/WSCgdShopper.dll?Handler=GenWSCgdShopperWSDL'  # Prod

shopperAudit = ET.Element("ShopperAudit", IPAddress='172.18.53.35', RequestedBy='bxberry', ID='9sd', Days='-1',
                          IncludeInitialAssignment='1')
returnFields = ET.SubElement(shopperAudit, "ReturnFields")

ET.SubElement(returnFields, 'Field', Name='birthDay')
ET.SubElement(returnFields, 'Field', Name='birthMonth')
ET.SubElement(returnFields, 'Field', Name='birthYear')
ET.SubElement(returnFields, 'Field', Name='city')
ET.SubElement(returnFields, 'Field', Name='company')
ET.SubElement(returnFields, 'Field', Name='country')
ET.SubElement(returnFields, 'Field', Name='dbp_emailFilterPreferenceID')
ET.SubElement(returnFields, 'Field', Name='dbp_shopperStatusID')
ET.SubElement(returnFields, 'Field', Name='doNotCallFlag')
ET.SubElement(returnFields, 'Field', Name='doNotEmailFlag')
ET.SubElement(returnFields, 'Field', Name='email')
ET.SubElement(returnFields, 'Field', Name='fax')
ET.SubElement(returnFields, 'Field', Name='first_name')
ET.SubElement(returnFields, 'Field', Name='fortKnox_shopperMobileAccountTypeID')
ET.SubElement(returnFields, 'Field', Name='fortKnox_shopperMobileCarrierID')
ET.SubElement(returnFields, 'Field', Name='fraud')
ET.SubElement(returnFields, 'Field', Name='gdshop_shopper_payment_type_id')
### The WSDs in GitHub say this field exists. They're lying.
# ET.SubElement(returnFields, 'Field', Name='fortKnox_paymentGroupID')
ET.SubElement(returnFields, 'Field', Name='gdshop_userTypeID')
ET.SubElement(returnFields, 'Field', Name='gender')
ET.SubElement(returnFields, 'Field', Name='hasRenewingServices')
ET.SubElement(returnFields, 'Field', Name='isCompany')
ET.SubElement(returnFields, 'Field', Name='isLocked')
ET.SubElement(returnFields, 'Field', Name='isPwdLocked')
ET.SubElement(returnFields, 'Field', Name='isStrongPassword')
ET.SubElement(returnFields, 'Field', Name='isUnified')
ET.SubElement(returnFields, 'Field', Name='last_changed_by')
ET.SubElement(returnFields, 'Field', Name='last_name')
ET.SubElement(returnFields, 'Field', Name='loginName')
ET.SubElement(returnFields, 'Field', Name='lu_emailTypeID')
ET.SubElement(returnFields, 'Field', Name='middle_name')
ET.SubElement(returnFields, 'Field', Name='mktg_email')
ET.SubElement(returnFields, 'Field', Name='mktg_mail')
ET.SubElement(returnFields, 'Field', Name='mktg_nonpromotional_notices')
ET.SubElement(returnFields, 'Field', Name='mktg_partner')
ET.SubElement(returnFields, 'Field', Name='mobilePhone')
ET.SubElement(returnFields, 'Field', Name='mobilePushNotification')
ET.SubElement(returnFields, 'Field', Name='parent_shopper_id')
ET.SubElement(returnFields, 'Field', Name='password')
ET.SubElement(returnFields, 'Field', Name='passwordHash')
ET.SubElement(returnFields, 'Field', Name='passwordReminder')
ET.SubElement(returnFields, 'Field', Name='payment')
ET.SubElement(returnFields, 'Field', Name='paymentProfilePurgeStatus')
ET.SubElement(returnFields, 'Field', Name='phone1')
ET.SubElement(returnFields, 'Field', Name='phone1Extension')
ET.SubElement(returnFields, 'Field', Name='phone2')
ET.SubElement(returnFields, 'Field', Name='privateLabelID')
ET.SubElement(returnFields, 'Field', Name='shipping_method')
ET.SubElement(returnFields, 'Field', Name='shopper_group_id')
ET.SubElement(returnFields, 'Field', Name='shopper_id')
ET.SubElement(returnFields, 'Field', Name='shopperPIN')
ET.SubElement(returnFields, 'Field', Name='state')
ET.SubElement(returnFields, 'Field', Name='status')
ET.SubElement(returnFields, 'Field', Name='street1')
ET.SubElement(returnFields, 'Field', Name='street2')
ET.SubElement(returnFields, 'Field', Name='validateOnlyWithPIN')
ET.SubElement(returnFields, 'Field', Name='zip')
ET.SubElement(returnFields, 'Field', Name='Currency')
ET.SubElement(returnFields, 'Field', Name='MarketID')
ET.SubElement(returnFields, 'Field', Name='CountrySiteID')
ET.SubElement(returnFields, 'Field', Name='externalID')
ET.SubElement(returnFields, 'Field', Name='organizationSize')
ET.SubElement(returnFields, 'Field', Name='ianaTimeZone')
xmlstr = ET.tostring(shopperAudit, encoding='utf8', method='xml')
# print xmlstr
result = Client(fkUrl).service.AuditShopper(xmlstr)
print result
