---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cmap-service"
  namespace: "abuse-api-prod"
  labels:
    app: "cmap-service"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "cmap-service"
  template:
    metadata:
      labels:
        app: "cmap-service"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      hostAliases:
        - ip: "10.33.199.15"
          hostnames:
            - "crmclient-api.prod.phx3.int.godaddy.com"
      containers:
        -
          name: "cmap-service"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/cmap_service:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            exec:
              command:
              - /app/kubetipper.sh
            initialDelaySeconds: 120
            periodSeconds: 120
            failureThreshold: 1
          env:
            - name: LOGLEVEL
              value: INFO
            - name: LIVENESS_TTL
              value: "7200"
            - name: LIVENESS_FACTOR
              value: "0.1"
            - name: BUILD_DATE
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
            - name: sysenv
              value: prod
            - name: HTTP_ONLY
              value: 'true'
            - name: CMAP_PROXY_USER
              valueFrom:
                secretKeyRef:
                  name: auth-cmap-proxy
                  key: username
            - name: CMAP_PROXY_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-cmap-proxy
                  key: password
            - name: CMAP_SERVICE_CERT
              value: /servicecerts/tls.crt
            - name: CMAP_SERVICE_KEY
              value: /servicecerts/tls.key
            - name: CMAP_PROXY_CERT
              value: /proxycerts/tls.crt
            - name: CMAP_PROXY_KEY
              value: /proxycerts/tls.key
            - name: CMAP_API_CERT
              value: /apicerts/tls.crt
            - name: CMAP_API_KEY
              value: /apicerts/tls.key
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-cmap-service
                  key: password
            - name: ALEXA_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-alexa
                  key: password
            - name: ALEXA_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: auth-alexa
                  key: username
            - name: VPS4_USER
              valueFrom:
                secretKeyRef:
                  name: auth-vps4-api
                  key: vps4user
            - name: VPS4_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-vps4-api
                  key: vps4pass
            - name: ANGELO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: angelouser
            - name: ANGELO_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: angelopass
            - name: DIABLO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: diablouser
            - name: DIABLO_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: diablopass
            - name: VERTIGO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: vertigouser
            - name: VERTIGO_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: vertigopass
            - name: MWP_ONE_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: mwponeuser
            - name: MWP_ONE_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: mwponepass
            - name: SMDB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-smdb
                  key: username
            - name: SMDB_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-smdb
                  key: password
            - name: VALUATION_KEY
              valueFrom:
                secretKeyRef:
                  name: valuation-api
                  key: password
          volumeMounts:
            - name: tls-files-proxy
              mountPath: /proxycerts
              readOnly: true
            - name: tls-files-api
              mountPath: /apicerts
              readOnly: true
            - name: tls-files-service
              mountPath: /servicecerts
              readOnly: true
      volumes:
        - name: tls-files-proxy
          secret:
            secretName: tls-cmap-auth
        - name: tls-files-api
          secret:
            secretName: tls-cmap-api
        - name: tls-files-service
          secret:
            secretName: tls-cmap-service
