---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "cmap-service"
  namespace: "abuse-api-prod"
  labels:
    app: "cmap-service"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "cmap-service"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "cmap-service"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/cmap_service:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: HTTP_ONLY
            value: 'true'
          - name: CMAP_PROXY_USER
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: username
          - name: CMAP_PROXY_PASS
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: password
          - name: CMAP_PROXY_CERT
            value: /proxycerts/tls.crt
          - name: CMAP_PROXY_KEY
            value: /proxycerts/tls.key
          - name: REDIS
            value: cmap-service-redis.abuse-api-prod.svc.cluster.local
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-cmap-service
                key: password

          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true
          - name: tls-files-proxy
            mountPath: /proxycerts
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files
        - name: tls-files-proxy
          secret:
            secretName: tls-cmap-auth
