apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- cmap_service.ingress.yaml

namespace: abuse-api-ote
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/livenessProbe"
      value:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 10
  target:
    kind: Deployment
    name: cmap-service

images:
- name: docker-dcu-local.artifactory.secureserver.net/cmap_service
  newTag: ote

configMapGenerator:
- literals:
  - METRICS_PORT='9200'
  - LOGLEVEL=INFO
  - sysenv=ote
  - HTTP_ONLY='true'
  - REDIS='cmap-service-redis.abuse-api-ote.svc.cluster.local'
  name: env-specific-values
