---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cmap-persistent-redis
  spec:
    storageClassName: managed-nfs-storage
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
