---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: cmap-service
  name: cmap-service
spec:
  ports:
    - name: cmap-service
      port: 5000
      targetPort: 5000
  selector:
    app: cmap-service
