---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmap-service
  labels:
    app: cmap-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cmap-service
  template:
    metadata:
      labels:
        app: cmap-service
    spec:
      imagePullSecrets:
        - name: artifactory-saas-creds
      hostAliases:
        - ip: "10.33.199.15"
          hostnames:
            - crmclient-api.prod.phx3.int.godaddy.com
      containers:
        - name: cmap-service
          image: gdartifactory1.jfrog.io/docker-dcu-local/cmap_service
          envFrom:
            - configMapRef:
                name: env-specific-values
          env:
            - name: CMAP_SERVICE_CLIENT_CERT
              value: /cmapservice-client-certs/tls.crt
            - name: CMAP_SERVICE_CLIENT_KEY
              value: /cmapservice-client-certs/tls.key
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-phishstory-v2
                  key: password
            - name: VPS4_USER
              valueFrom:
                secretKeyRef:
                  name: auth-vps4-api
                  key: vps4user
            - name: VPS4_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-vps4-api
                  key: vps4pass
            - name: ANGELO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: angelouser
            - name: ANGELO_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: angelopass
            - name: DIABLO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: diablouser
            - name: DIABLO_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-hosting-envs
                  key: diablopass
            - name: NETBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netbox-token
                  key: token
            - name: VALUATION_KEY
              valueFrom:
                secretKeyRef:
                  name: valuation-api
                  key: password
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: secret
            - name: MONGO_CLIENT_CERT
              value: /mongo_common_certs/mongo_client.pem
          volumeMounts:
            - name: tls-files-api
              mountPath: /apicerts
              readOnly: true
            - name: tls-files-cmapservice-client-cert
              mountPath: /cmapservice-client-certs
              readOnly: true
            - name: tls-mongo-common-cert-files
              mountPath: /mongo_common_certs
              readOnly: true
      volumes:
        - name: tls-files-api
          secret:
            secretName: tls-cmap-api
        - name: tls-files-cmapservice-client-cert
          secret:
            secretName: tls-cmapservice-client-cert
        - name: tls-mongo-common-cert-files
          secret:
            secretName: tls-mongo-common-cert-files