---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmap-service-redis
  labels:
    app: cmap-service-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmap-service-redis
  template:
    metadata:
      labels:
        app: cmap-service-redis
    spec:
      imagePullSecrets:
        - name: artifactory-saas-creds
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - "redis-cli ping"